#!/usr/bin/env bash

# Creates a configuration file with version-pinned CNI manifest URLs.
# This file can be sourced by deployment scripts to decouple them from specific versions.

set -o pipefail

source "${LIB_CORE_SH}"
source "${LIB_OS_SH}"

lib::strict
lib::setup_traps
lib::require_root

readonly CONFIG_FILE="/etc/k8s-cni.conf"

main() {
  lib::header "Generating CNI Manifest Configuration"

  lib::log "Creating CNI config file at ${CONFIG_FILE}"
  # Start with a clean file and add a header
  {
    echo "# Generated by Packer during image build on $(date)"
    echo "# This file contains the version-pinned URLs for CNI manifests."
    echo
  } > "${CONFIG_FILE}"

  # --- CNI Version and URL Definitions ---
  # These are read from the environment variables passed by Packer.
  local cni_calico_version="${CNI_CALICO_VERSION:-v3.27.3}"
  local cni_flannel_version="${CNI_FLANNEL_VERSION:-v0.25.1}"
  # The flannel plugin version isn't used for the manifest URL, but the var is available.

  # Construct the URLs
  local calico_url="https://raw.githubusercontent.com/projectcalico/calico/${cni_calico_version}/manifests/calico.yaml"
  local flannel_url="https://raw.githubusercontent.com/flannel-io/flannel/${cni_flannel_version}/Documentation/kube-flannel.yml"

  # Write the export lines to the config file
  {
    echo "export CNI_MANIFEST_CALICO=\"${calico_url}\""
    echo "export CNI_MANIFEST_FLANNEL=\"${flannel_url}\""
  } >> "${CONFIG_FILE}"

  # Set permissions
  chmod 0644 "${CONFIG_FILE}"

  lib::success "Successfully generated CNI manifest config."
  lib::log "Contents of ${CONFIG_FILE}:"
  # Indent the cat output for better log readability
  sed 's/^/    /' "${CONFIG_FILE}"
}

main "$@"
