#!/bin/bash
# scripts/publish_to_vagrant_cloud.sh
# Publishes a Vagrant box to Vagrant Cloud using metadata JSON generated by make vagrant-metadata
# Usage: ./scripts/publish_to_vagrant_cloud.sh <metadata_json_file>

set -euo pipefail

# Colors
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
RESET='\033[0m'

API_BASE="https://app.vagrantup.com/api/v1"

# Check dependencies
for cmd in jq curl; do
    if ! command -v $cmd &> /dev/null; then
        echo -e "${RED}Error: $cmd is required but not installed.${RESET}"
        exit 1
    fi
done

# Check arguments
if [ "$#" -ne 1 ]; then
    echo -e "${RED}Usage: $0 <metadata_json_file>${RESET}"
    exit 1
fi

METADATA_FILE="$1"
if [ ! -f "$METADATA_FILE" ]; then
    echo -e "${RED}Error: Metadata file '$METADATA_FILE' not found.${RESET}"
    exit 1
fi

# Check token
if [ -z "${VAGRANT_CLOUD_TOKEN:-}" ]; then
    echo -e "${RED}Error: VAGRANT_CLOUD_TOKEN environment variable is not set.${RESET}"
    echo "Please export your Vagrant Cloud API token:"
    echo "export VAGRANT_CLOUD_TOKEN='your_token_here'"
    exit 1
fi

log() { echo -e "${GREEN}[publish] $1${RESET}"; }
warn() { echo -e "${YELLOW}[publish] $1${RESET}"; }
err() { echo -e "${RED}[publish] $1${RESET}"; }

# Parse Metadata
log "Parsing metadata from $METADATA_FILE..."
BOX_TAG=$(jq -r '.name' "$METADATA_FILE")
BOX_DESC=$(jq -r '.description' "$METADATA_FILE")
VERSION=$(jq -r '.versions[0].version' "$METADATA_FILE")
PROVIDER_NAME=$(jq -r '.versions[0].providers[0].name' "$METADATA_FILE")
BOX_FILE_URL=$(jq -r '.versions[0].providers[0].url' "$METADATA_FILE")
CHECKSUM=$(jq -r '.versions[0].providers[0].checksum' "$METADATA_FILE")
CHECKSUM_TYPE=$(jq -r '.versions[0].providers[0].checksum_type' "$METADATA_FILE")

# Convert file:// URL to local path
if [[ "$BOX_FILE_URL" == file://* ]]; then
    BOX_FILE_PATH="${BOX_FILE_URL#file://}"
else
    BOX_FILE_PATH="$BOX_FILE_URL"
fi

if [ ! -f "$BOX_FILE_PATH" ]; then
    err "Box file not found at: $BOX_FILE_PATH"
    echo "Current directory: $(pwd)"
    exit 1
fi

USERNAME=$(echo "$BOX_TAG" | cut -d'/' -f1)
BOX_NAME=$(echo "$BOX_TAG" | cut -d'/' -f2)

log "Configuration:"
echo "  Box:       $BOX_TAG"
echo "  Version:   $VERSION"
echo "  Provider:  $PROVIDER_NAME"
echo "  File:      $BOX_FILE_PATH"
echo "  Size:      $(du -h "$BOX_FILE_PATH" | cut -f1)"

# Helper for API requests
api_req() {
    local method="$1"
    local endpoint="$2"
    local data="${3:-}"
    
    local args=(-s -X "$method" -H "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" -H "Content-Type: application/json")
    
    if [ -n "$data" ]; then
        args+=(-d "$data")
    fi
    
    curl "${args[@]}" "${API_BASE}${endpoint}"
}

# 1. Ensure Box exists
log "Checking if box $BOX_TAG exists..."
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" "${API_BASE}/box/$BOX_TAG")

if [ "$HTTP_CODE" == "404" ]; then
    log "Box $BOX_TAG does not exist. Creating..."
    PAYLOAD=$(jq -n --arg name "$BOX_NAME" --arg desc "$BOX_DESC" \
        '{ "box": { "name": $name, "description": $desc, "is_private": false } }')
    
    RESPONSE=$(api_req POST "/boxes" "$PAYLOAD")
    
    if echo "$RESPONSE" | jq -e '.errors' >/dev/null; then
        err "Failed to create box: $(echo "$RESPONSE" | jq -r '.errors[]')"
        exit 1
    fi
    log "Box created successfully."
else
    log "Box exists."
fi

# 2. Ensure Version exists
log "Checking/Creating version $VERSION..."
PAYLOAD=$(jq -n --arg ver "$VERSION" '{ "version": { "version": $ver } }')
RESPONSE=$(api_req POST "/box/$BOX_TAG/versions" "$PAYLOAD")

if echo "$RESPONSE" | jq -e '.errors' >/dev/null; then
    # It might fail if it already exists, which is fine, check strictly
    ERR=$(echo "$RESPONSE" | jq -r '.errors[]')
    if [[ "$ERR" == *"Version already exists"* ]]; then
        warn "Version $VERSION already exists."
    else
        err "Failed to create version: $ERR"
        exit 1
    fi
else
    log "Version created/verified."
fi

# 3. Create Provider
log "Creating provider '$PROVIDER_NAME' for version $VERSION..."

PAYLOAD=$(jq -n --arg name "$PROVIDER_NAME" --arg csum "$CHECKSUM" --arg ctype "$CHECKSUM_TYPE" \
    '{ "provider": { "name": $name, "checksum": $csum, "checksum_type": $ctype } }')

RESPONSE=$(api_req POST "/box/$BOX_TAG/version/$VERSION/providers" "$PAYLOAD")

if echo "$RESPONSE" | jq -e '.errors' >/dev/null; then
    ERR=$(echo "$RESPONSE" | jq -r '.errors[]')
    if [[ "$ERR" == *"Provider already exists"* ]]; then
        warn "Provider already exists. Checking state..."
        # We can't easily check if the upload is complete, but we can't re-upload without deleting.
        err "Provider '$PROVIDER_NAME' already exists for version $VERSION."
        err "To re-upload: Delete the provider (or version) on Vagrant Cloud first."
        exit 1
    else
        err "Failed to create provider: $ERR"
        exit 1
    fi
fi

UPLOAD_URL=$(echo "$RESPONSE" | jq -r '.upload_url')
log "Provider created. Got upload URL."

# 4. Upload File
log "Uploading box file (this may take a while)..."
# Use --progress-bar for better visual
curl --progress-bar -X PUT --upload-file "$BOX_FILE_PATH" "$UPLOAD_URL"
echo "" # Newline
log "Upload complete."

# 5. Release Version
log "Releasing version $VERSION..."
RESPONSE=$(api_req PUT "/box/$BOX_TAG/version/$VERSION/release")

if echo "$RESPONSE" | jq -e '.errors' >/dev/null; then
    err "Failed to release version: $(echo "$RESPONSE" | jq -r '.errors[]')"
    exit 1
fi

log "SUCCESS! Box $BOX_TAG v$VERSION ($PROVIDER_NAME) is published and released."
echo "View at: https://app.vagrantup.com/$BOX_TAG"
